# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.8

    branches:
      only:
        - master

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Test Build
          command: yarn test

      # Setup Git
      - run:
          name: Setup Git
          command: |
            git config --global user.email "octarine-bot@octarinegroup.com"
            git config --global user.name "OctarineBot"
            git remote rm origin
            git remote add origin https://octarine-bot:${GITHUB_TOKEN}@github.com/octarinegroup/aurum-fx.git

      # Deploy Static files!
      - run:
          name: yarn deploy
          command: yarn deploy